### ISSUE TITLE
0.7 released and this version doesn't byte compile

### ISSUE THREAD

**Issue by aaronjensen** [emacsorphanage/undo-tree#1]
Hi @tarsius, thanks for keeping this alive and updated for so long. I noticed today that b230d47 breaks byte-compile when used with evil. I get this when `(undo-tree 1)` is invoked while byte compiling:

```
Cannot load evil: (wrong-type-argument number-or-marker-p nil)
```

Also, it seems that Toby Cubitt released version 0.7 to ELPA yesterday (!), though it still appears to depend on `cl`.

**Comment by tarsius** [comment]
> I noticed today that b230d47 breaks byte-compile when used with evil.

Are you sure it's because of that commit?
Did you try without any of my commits?
Did you try removing undo-tree, restarting Emacs and only then reinstalling it?

> Also, it seems that Toby Cubitt released version 0.7 to ELPA yesterday (!),

I am aware. I heard about it here: https://www.reddit.com/r/emacs/comments/elg8hw/toby_qubit_cubitt_lost_or_corrupted_undotree/.

(This thread also mentions similar sounding issues and they appear to be related to evil too.)

> though it still appears to depend on `cl`.

I have not submitted my commit that changes that to him and don't plan to do it. I have tried with some of my other commits but that did not lead anywhere. Mostly my patches just address minor issues the byte-compiler complains about. I care about such things ^1 but the maintainer apparently not so much.

1: In all packages that I have installed. Most packages that I use have zero warnings, many of them because I am using them. If one package does not address warnings for years and even though I send patches and several reminders and pleas, then eventually I will fork that package, even just to fix those minor issues.

**Comment by aaronjensen** [comment]
Sorry, I didn't see that you had incorporated 0.7's changes here. Now that that's clear, I bisected and the actual problem commit is https://github.com/emacsorphanage/undo-tree/commit/e6f31a053c41a1233c27185c4f31d6856d25b3d7

Apparently `undo-outer-limit` is `nil` while compiling in batch mode, so `max` fails. This is perhaps only a 27 issue, which I can work around. 

I could submit a PR here if you like to deal w/ the nil case. In any case, no bug in this repo, so closing.

Thanks!

**Comment by tarsius** [comment]
You should probably let Toby know about it instead of submitting a patch here.

**Comment by aaronjensen** [comment]
Good call, I guess I was discouraged by your experience, but I've done that. Thanks.

**Comment by tarsius** [comment]
Well my changes can be somewhat reasonably be classified as nitpicking. But your case seems different--a bug is a bug. I am sure he is interested in fixing that.
